name: thd_analysis
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  chinese_font_library: ^1.0.0
  provider: ^6.1.4
  flutter_libserialport:
    git:
      url: https://github.com/canxin121/flutter_libserialport
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  package_rename: ^1.10.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

package_rename_config:
  android:
    app_name: ThdAnalysis
    package_name: com.canxin.thd.analysis

  linux:
    app_name: ThdAnalysis
    package_name: com.canxin.thd.analysis
    exe_name: thd_analysis 

  macos:
    app_name: ThdAnalysis
    package_name: com.canxin.thd.analysis

  windows:
    app_name: ThdAnalysis
    exe_name: thd_analysis 
